### ISSUE TITLE
Issue with filepath for keyfile

### ISSUE THREAD

**Issue by omkarpg0931** [CyberSource/cybersource-rest-client-node#10]
Hi,

I was testing your module for my project on Linux with Node.js v8.13.
The concatenated path string for path.resolve functionality in "fetchCachedCertificate" function in file authentication/util/Cache.js does not work on Linux as the filepath is created with `\\`, which is supported on Windows only.
On Linux, `/` is supported by `path` npm module.

**Comment by taminhtien** [comment]
Same to me. Is this library stable to use in production?

**Comment by weisurya** [comment]
Hey, any timeline on fixing this issue? I also found several issues on other clients that related to OS

**Comment by gnongsie** [comment]
Hi,
A fix for this has been released in v0.0.18. Can you validate the fix?

**Comment by chengkiang** [comment]
This can be fixed. The error is in the package cybersource-auth-rest.

Go to ./node_modules/cybersource-rest-auth/src/com/cybersource/authentication/util/Cache.js, line 20:

```
var filePath = path.resolve(merchantConfig.getKeysDirectory() + '\\' + merchantConfig.getKeyFileName() + '.p12');
```
Change it to "/"

```
var filePath = path.resolve(merchantConfig.getKeysDirectory() + '/' + merchantConfig.getKeyFileName() + '.p12');
```

There is a similar bug in the logging. The file is at node_modules/cybersource-rest-auth/src/com/cybersource/authentication/util/Logger.js

```
var newPath = fileDirectory + "\\" + newFileName;
```

should be changed to

```
var newPath = fileDirectory + "/" + newFileName;
```

Unfortunately, I can't find the Github repo of that package to do a pull request.

**Comment by ejames17** [comment]
same issue here
