### ISSUE TITLE
dependency on vm2 which has critical security vulnerabilities

### ISSUE THREAD

**Issue by zakyg** [CyberSource/cybersource-rest-client-node#113]
installing 0.0.48 via npm warns that the package depends on vm2 which has critical security vulnerabilities. the vm2 package warns that the package is deprecated the advices to migrate to isolated-vm.
https://www.npmjs.com/package/vm2

**Comment by FerMeichtri** [comment]
Same problem here. Is this going to be fixed soon?

I also encountered the problem "jwk-to-pem dependency missing"

**Comment by tgayvert** [comment]
Are there any updates on the cybersource side for this? Are there any plans to resolve this or implement some of the workarounds described in: https://github.com/TooTallNate/superagent-proxy/issues/48

It looks like there has been progress made to fix in the other upstream dependencies: https://github.com/TooTallNate/proxy-agents/pull/224

**Comment by monu-kumar-visa** [comment]
Superagent-proxy has been removed as a dependency starting from version v0.0.51. Please use version v0.0.51 or later.
