### ISSUE TITLE
How to provide fingerprint session id when authorizing a payment or tokenizing a card?

### ISSUE THREAD

**Issue by francisbrito** [CyberSource/cybersource-rest-client-node#25]
In Simple Order API and Secure Acceptance Checkout API, it is possible to provide a device fingerprint when making an authorization or tokenization using the fields `deviceFingerprintID` (Simple Order API) and  `device_fingerprint_id` (Checkout API). From a quick search in this repository, I can see there is a field called `fingerprintSessionId` which seems to have the same structure but is only available for creating Decision Manager cases.

Can `fingerprintSessionId` be provided when making an authorization or tokenization? If so, where can I find documentation on how to do so? If not, what alternative do I have to provide device fingerprint information to CyberSource when using RESTful API?

**Comment by chandru9279** [comment]
I hit this as well. @francisbrito any updates? Did you close because it was solved?

**Comment by francisbrito** [comment]
@chandru9279 I'm afraid not. I ended up closing the issue due to lack of response.

I ended up sticking to Simple Order API + Checkout API for authorizations and tokenizations, respectively.

**Comment by chandru9279** [comment]
Thank you.
In the end, this was solved for me by using the DF tags (Device fingerprint Tag - its a tiny javascript include).
Using the same session ID 
1. when including the DF tag (in the web UI), and 
2. when making the payment call 
helped to fix my issue. The session id helps CYBS to correlate the fingerprint that was generated by the DF tag, and the backend REST api calls we make.

**Comment by nanettaboadafriass** [comment]
Hello I have the same problem, I already added the DF scripts and I am sending the session_id in fingerprintSessionId using api rest from cybersource, in the transaction management panel I still get the fingerprint was not sent

**Comment by chandru9279** [comment]
when adding the DF script, did you add the same ID in the url
`<script type='.....' src='......?sessionid={exactmatchingsessionid}>`

**Comment by nanettaboadafriass** [comment]
I have added these scripts
inside the head tag:
`<script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id={{$df_org_id}}&session_id={{$merchant_id}}{{$session_id}}"></script>`
and inside the body tag:
```
<noscript>
 <iframe style="width: 100px; height: 100px; border: 0; position:absolute; top: -5000px;" 
src="https://h.online-metrix.net/fp/tags?org_id={{$df_org_id}}&session_id={{$merchant_id}}{{$session_id}}"></iframe>
 </noscript>
```
As indicated by the cybersource documentation
Using the cybersource API specifically in the payment process, I make a request using ajax from the view that contains the fingerprint scripts
`https://apitest.cybersource.com/pts/v2/payments`
and sending the following information
```
{
  "clientReferenceInformation": {
    "code": "54323007"
  },
  "paymentInformation": {
    "card": {
      "number": "4444444444444448",
      "expirationMonth": "12",
      "expirationYear": "2020"
    }
  },
  "orderInformation": {
    "amountDetails": {
      "totalAmount": "144.14",
      "currency": "USD"
    },
    "billTo": {
      "firstName": "James",
      "lastName": "Smith",
      "address1": "96, powers street",
      "locality": "Clearwater milford",
      "administrativeArea": ​​"NH",
      "postalCode": "03055",
      "country": "US",
      "email": "test@visa.com",
      "phoneNumber": "7606160717"
    }
  },
  "deviceInformation": {
    "hostName": "host.com",
    "ipAddress": "64.124.61.215",
    "userAgent": "Chrome",
    "fingerprintSessionId": "xxxxxxxxxxxxxxxxxxxxxx",
    "httpBrowserEmail": "xyz@gmail.com"
  }
}
```
in `fingerprintSessionId` I already tried sending only $session_id and also {{$merchant_id}}{{$ session_id}} together, even in cybersource transaction panel in continuous fingerprint not submited

**Comment by chandru9279** [comment]
Seems like u are doing everything right. The script tag should have both {{$merchant_id}}{{$session_id}} and the input hidden and subsequent call to payments api should have just the {{$session_id}}.  If all this is correct.. perhaps you have a different org id that you need to use. (Its normal to have different orgid between prod and test) Cybersource is not able to find the session, using ur session id.. hence no fingerprint appears. It may be looking in the wrong org

**Comment by nanettaboadafriass** [comment]
I still can't find a solution to this issue, looking at the api rest documentation from cybersource I saw in `deviceInformation`, there is an array called `rawData` that should be sent with data from the fingerprint.
```
  "deviceInformation": {
     "hostName": "",
     "ipAddress": "",
     "userAgent": "",
     "fingerprintSessionId": "",
     "rawData": [
       {
         "data": "",
         "provider": ""
       }]
}
```

**Comment by francisbrito** [comment]
@nanettaboadafriass could you please confirm if device fingerprinting is enabled in your CyberSource profile? If you do not have access to the profile configuration, ask your integration assistant to check for you.

If DF is enabled, could you please confirm if the DF script is been loaded and executed correctly? You can verify this by having a look at the network and console activity in your preferred browser.

If both these look OK, I'd suggest you scale the situation to your integration assistant, and if possible, open a debug session with them. That way they can indicate whether the DF is being received or not by CYBS servers.

**Comment by nanettaboadafriass** [comment]
@francisbrito Thank you very much, I managed to solve the problem in short the `org_id` was the problem, cybersource a few weeks ago I updated the credentials.

**Comment by francisbrito** [comment]
I'm happy to hear your issue was solved @nanettaboadafriass.

**Comment by pedrouci92** [comment]
Could you share your answer? I have exactly the same problem you had

**Comment by nanettaboadafriass** [comment]
The problem was configuring the fingerprint script with the wrong `org_id`, I spoke to the cybersource providers in my country and they gave me an updated `org_id` and it worked for me, remember that there are two types of org_id one for test and one for production, check that the fingerprint script is loading correctly in your browser in the network section of the development console

**Comment by bnapky** [comment]
@nanettaboadafriass  

1snn5n9w | sandbox
k8vif92e | production

Are these the org_id values you used in the end or do you mean they gave you other values?

**Comment by andeanbiz** [comment]
> Thank you.
> In the end, this was solved for me by using the DF tags (Device fingerprint Tag - its a tiny javascript include).
> Using the same session ID
> 
> 1. when including the DF tag (in the web UI), and
> 2. when making the payment call
>    helped to fix my issue. The session id helps CYBS to correlate the fingerprint that was generated by the DF tag, and the backend REST api calls we make.

Anyone that can help me with fingerprint generation? My Skype andeanbizz

**Comment by linwh** [comment]
> @nanettaboadafriass
> 
> 1snn5n9w | sandbox k8vif92e | production
> 
> Are these the org_id values you used in the end or do you mean they gave you other values?

May I ask how you accessed the org_id? Can it be seen in the CyberSource backend, or do I need to contact the official technical team? I am using the Sandbox environment.

**Comment by nanettaboadafriass** [comment]
If those are the values ​​I used for the org_id, my cybersource provider sent it to me, you can ask your provider for those values.

**Comment by linwh** [comment]
> Yes, those are the values ​​I used for the org_id, my cybersource provider sent it to me, you can ask your provider for those values.

Thank you very much! However, I registered for the sandbox account myself. How can I find out my org_id?
