### ISSUE TITLE
Docs Down

### ISSUE THREAD

**Issue by tooolbox** [CyberSource/cybersource-rest-client-node#44]
(This has nothing to do with the Node SDK but I'm not sure where else to put this.)

https://developer.cybersource.com/library/documentation/dev_guides/REST_API/payments_api.html

> Oops... ReDoc failed to render this spec
Error parsing https://developer.cybersource.com/library/documentation/dev_guides/REST_API/payments-swagger.json end of the stream or a document separator is expected at line 16, column 66: ... =w[l]||[];w[l].push({'gtm.start': ^

**Comment by brianmc** [comment]
Thanks @tooolbox where did you find this link?  It seems like an old one that we need to update.

**Comment by tooolbox** [comment]
No problem, I Googled `cybersource swagger api` and it was the second hit.
