### ISSUE TITLE
Undeclared dependency jwk-to-pem

### ISSUE THREAD

**Issue by doginthehat** [CyberSource/cybersource-rest-client-node#47]
The client package requires `jwk-to-pem` to work but it is not listed in the package's own dependencies.

Installing the client results in error `Error: Cannot find module 'jwk-to-pem'`

**Comment by caub** [comment]
@gnongsie or @rsachan8 it's just moving jwk-to-pem from devDependencies to dependencies, else `npm i --production` won't work as described

simple fix, do you want a PR?
