### ISSUE TITLE
Problem with modifications to Array.prototype.from in transitive dependency breaks other packages

### ISSUE THREAD

**Issue by sgronblo** [CyberSource/cybersource-rest-client-node#49]
## Summary:

`collections` breaks `Array.from` which causes other npm packages to stop working

### Details:

`cybersource-rest-client` 0.0.20 depends on
`cybersource-rest-auth` 0.0.7 depends on
`collections` 5.1.11

`collections` includes an incorrect modification of `Array.from` which creates problems for other packages that use `Array.from`. We discovered this when using `testcontainers-node` which has a transitive dependency which stops working because of the incorrect overriding of `Array.from`.

It seems that `cybersource-rest-auth` only uses collections for `Map`.

### Suggestions/Questions:

- Is cybersource-rest-auth no longer available on Github? How do we fix this problem in the long term?
- Since you only use map from `collections`, would you consider replacing it with a different library? It seems to not be very actively maintained any more and it seems to have a philosophy of augmenting object prototypes which risks causing breakage in your customer's software in the future.

**Comment by sgronblo** [comment]
`collections` has released an update that removes this breakage. If you reinstall `collections` now you should be getting the latest version. However, I still think you should move away from dependencies that may risk breaking your users other code (such as by modifying object prototypes).

**Comment by uPaymeiFixit** [comment]
Confirmed [collections v5.1.13](https://www.npmjs.com/package/collections) still breaks Map in certain use-cases. I've submitted a [PR](https://github.com/CyberSource/cybersource-rest-client-node/pull/100) to remove this dependency.

**Comment by monu-kumar-visa** [comment]
Hi @uPaymeiFixit 
We have updated our library to no longer require collections as a dependency. Kindly use the most recent version.

**Comment by uPaymeiFixit** [comment]
I noticed that. Instead of accepting my pull request it looks like @gaubansa may have copied my code (excluding the fixed typos) and manually merged it in. ([My PR](https://github.com/CyberSource/cybersource-rest-client-node/pull/100/files) vs. @gaubansa's [commit](https://github.com/CyberSource/cybersource-rest-client-node/commit/99ab0e46594416deff4ff4b548f103dd689bfc0e)) Out of curiosity is there a reason for that?
