### ISSUE TITLE
node-forge  <=0.9.2

### ISSUE THREAD

**Issue by paintsis** [CyberSource/cybersource-rest-client-node#51]
node-forge  <=0.9.2
Severity: high
Prototype Pollution in node-forge - https://npmjs.com/advisories/1561
No fix available
node_modules/cybersource-rest-auth/node_modules/node-forge
  cybersource-rest-auth  *
  Depends on vulnerable versions of node-forge
  node_modules/cybersource-rest-auth
    cybersource-rest-client  *
    Depends on vulnerable versions of cybersource-rest-auth
    node_modules/cybersource-rest-client

3 high severity vulnerabilities

**Comment by monu-kumar-visa** [comment]
We have updated node-forge and many other dependencies that our library uses in our latest releases.
