### ISSUE TITLE
Onboard Merchant API question

### ISSUE THREAD

**Issue by pepchit01** [CyberSource/cybersource-rest-client-node#85]
Hi,
I would like to create a merchant boarding registration through an API call. Do you have this example?

**Comment by samhithal** [comment]
hello @pepchit01, you can look through this link for merchant boarding - https://developer.cybersource.com/api-reference-assets/index.html?stage=pilot#merchant-boarding
Thank you for the suggestion. We will consider adding boarding registration product to the SDKs.

**Comment by monu-kumar-visa** [comment]
Hi @pepchit01 
We have added the merchant-onboarding API in version 0.0.51 and onwards. Please use the latest version.
