### ISSUE TITLE
Incorrect condition in ExternalLoggerWrapper.isLoggerEmpty()

### ISSUE THREAD

**Issue by sgronblo** [CyberSource/cybersource-rest-client-node#96]
The current implementation is: https://github.com/CyberSource/cybersource-rest-client-node/blob/2bea814af808e070bd0f4c735de29f2b571fa799/src/authentication/logging/ExternalLoggerWrapper.js#L15

But surely this should be true when the `externalLogger === undefined`, and not the other way?

Also you don't need to return true and false. You can just change it to:

```
    isLoggerEmpty() {
        return this.extLogger !== undefined
    }
```

If you want to make it more robust also for environments running older versions of ECMAScript, you should actually use `typeof this.extLogger !== 'undefined'`: https://stackoverflow.com/questions/3390396/how-can-i-check-for-undefined-in-javascript

**Comment by rsachan8** [comment]
@sgronblo Thanks for identifying this issue. Function name is ambiguous to the way its being used. Will rollout a fix in next release.

**Comment by rsachan8** [comment]
This issue is fixed in latest release.
