### ISSUE TITLE
No valid external logger object found. Turning off external logger flag exception handling

### ISSUE THREAD

**Issue by iantmc87** [CyberSource/cybersource-rest-client-node#97]
After upgrading to the latest version (0.0.40) we are seeing this error in our logs  - **No valid external logger object found. Turning off external logger flag.**

Which gets logged out by line 133 in src/authentication/logging/LogConfiguration.js () within this if statement - 

```
if((typeof (this.externalLogger) === "object" && !(this.externalLogger instanceof ExternalLoggerWrapper))
    || this.externalLogger === undefined || !(this.externalLogger.isLoggerEmpty())){
       ApiException.LoggerException("No valid external logger object found. Turning off external logger flag.")
       this.hasExternalLogger = false;
}
```

For us this will be because this.externalLogger will be undefined as we haven't set it in the logConfiguration object. We also haven't set the hasExternalLogger flag which gets set to false if missing just above this code on line 128.

As we haven't specified a value for hasExternalLogger, then I don't think this exception shouldn't be getting hit and logging an error, as this.hasExternalLogger is already set to false on line 128 so don't think you need to be checking for an externalLogger object when hasExternalLogger is false as there won't be a logger object, and all you are doing in this case is logging out the error and setting the value to false again.

**Comment by rsachan8** [comment]
This issue is fixed in latest release.
